### Get all levels
GET http://localhost:3000/api/v1/levels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNTg0MzAyMDk0LCJleHAiOjE1ODk0ODYwOTR9.EyoEfkFQc7VDScW_ATOG1JXThzBHGqlP24o3SHyOsBQ

### Add a level
POST http://localhost:3000/api/v1/levels/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNTg0MzAyMDk0LCJleHAiOjE1ODk0ODYwOTR9.EyoEfkFQc7VDScW_ATOG1JXThzBHGqlP24o3SHyOsBQ

{
    "name": "novice",
    "description": "New unregistered member level",
    "access": 0,
    "rights": "0",
    "status": 1
}

### Get level details
GET http://localhost:3000/api/v1/levels/5e70f7ae1fafe01dc8d55eed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNTg0MzAyMDk0LCJleHAiOjE1ODk0ODYwOTR9.EyoEfkFQc7VDScW_ATOG1JXThzBHGqlP24o3SHyOsBQ

### Update level details
PATCH http://localhost:3000/api/v1/levels/5e70fb221fafe01dc8d55ef2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNTg0MzAyMDk0LCJleHAiOjE1ODk0ODYwOTR9.EyoEfkFQc7VDScW_ATOG1JXThzBHGqlP24o3SHyOsBQ

{
    "description": "Unregistered newbie on trial"
}

### Delete a specific level
DELETE http://localhost:3000/api/v1/levels/5e70fb221fafe01dc8d55ef2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNTg0MzAyMDk0LCJleHAiOjE1ODk0ODYwOTR9.EyoEfkFQc7VDScW_ATOG1JXThzBHGqlP24o3SHyOsBQ
